# Generated by Django 4.1.1 on 2022-10-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("className", models.CharField(blank=True, max_length=20, null=True)),
                ("head", models.CharField(blank=True, max_length=20, null=True)),
                ("headClass", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReportInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("koTitle", models.CharField(max_length=50)),
                ("enTitle", models.CharField(max_length=50)),
                ("thumbNail", models.ImageField(upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReportInputString",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "textChar",
                    models.CharField(choices=[("p", "p"), ("h2", "h2")], max_length=2),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_text",
                        to="reportInput.paragraph",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SharedText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snsChoices",
                    models.CharField(
                        choices=[
                            ("twitter", "twitter"),
                            ("instagram", "instagram"),
                            ("facebook", "facebook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("snsID", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_shared",
                        to="reportInput.reportinputstring",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paragraph",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="reportInput.reportinput",
            ),
        ),
    ]
