# Generated by Django 4.1.1 on 2022-10-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportInput", "0002_alter_paragraph_classname_alter_paragraph_head_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="paraClass",
            field=models.CharField(
                choices=[("reportPara", "reportPara"), ("hr", "hr")],
                default="reportPara",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="headClass",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BoldnUnder", "BoldnUnder"),
                    ("Bold", "Bold"),
                    ("narrowNum", "narrowNum"),
                ],
                max_length=60,
                null=True,
            ),
        ),
    ]
