# Generated by Django 4.1.1 on 2022-10-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportInput", "0003_paragraph_paraclass_alter_paragraph_headclass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportinputstring",
            name="text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
