# Generated by Django 4.1.1 on 2022-10-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportInput", "0004_alter_reportinputstring_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paragraph",
            name="headClass",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BoldnUnder", "BoldnUnder"),
                    ("Bold", "Bold"),
                    ("narrowNum", "narrowNum"),
                ],
                default="Bold",
                max_length=60,
                null=True,
            ),
        ),
    ]
